# Generated by Django 4.2.9 on 2026-03-07 10:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRE_SCHOOL", "Pre-School"),
                            ("PRIMARY", "Primary"),
                            ("JHS", "JHS"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "jhs_extra_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Extra fee for JHS classes",
                        max_digits=10,
                    ),
                ),
                (
                    "jhs3_extra_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional fee for JHS 3 only",
                        max_digits=10,
                    ),
                ),
                (
                    "saturday_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saturday class fee",
                        max_digits=10,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "school_classes",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        default="E.P Basic School Ashaiman", max_length=200
                    ),
                ),
                (
                    "school_motto",
                    models.CharField(
                        default="Excellence Through Discipline", max_length=200
                    ),
                ),
                (
                    "school_address",
                    models.TextField(default="Ashaiman, Greater Accra Region, Ghana"),
                ),
                ("school_phone", models.CharField(blank=True, max_length=20)),
                ("school_email", models.EmailField(blank=True, max_length=254)),
                ("school_po_box", models.CharField(blank=True, max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school/logo/"),
                ),
                (
                    "school_retention_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Percentage retained by school",
                        max_digits=5,
                    ),
                ),
                (
                    "admin_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Administrative fee percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "report_header_color",
                    models.CharField(default="#1a365d", max_length=7),
                ),
                ("watermark_opacity", models.FloatField(default=0.06)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
                "db_table": "school_settings",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("admission_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TRANSFERRED", "Transferred"),
                            ("GRADUATED", "Graduated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=15)),
                ("parent_phone_alt", models.CharField(blank=True, max_length=15)),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("has_fee_exemption", models.BooleanField(default=False)),
                (
                    "exemption_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("exemption_reason", models.TextField(blank=True)),
                ("exemption_valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["school_class", "last_name", "first_name"],
            },
        ),
    ]
