# Generated by Django 4.2.9 on 2026-03-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="exemption_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_exemptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="school.schoolclass",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["category"], name="school_clas_categor_5488e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["is_active"], name="school_clas_is_acti_f307ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school_class", "status"], name="students_school__4f3ea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id"], name="students_student_1ff8ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"], name="students_last_na_08ef26_idx"
            ),
        ),
    ]
