# Generated by Django 4.2.9 on 2026-03-08 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="logo_watermark",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated faded version for watermarks",
                null=True,
                upload_to="school/watermark/",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="report_accent_color",
            field=models.CharField(default="#3182ce", max_length=7),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school/logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="school_motto",
            field=models.CharField(default="Now Or Never", max_length=200),
        ),
    ]
