# Generated by Django 4.2.9 on 2026-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("SESSION_TRANSITION", "Session Transition"),
                            ("APPROVAL", "Approval"),
                            ("REJECTION", "Rejection"),
                            ("DISTRIBUTION", "Distribution"),
                            ("EXPORT", "Export/Download"),
                            ("UNLOCK", "Session Unlock"),
                            ("ARREARS_PAYMENT", "Arrears Payment"),
                            ("FEE_WAIVER", "Fee Waiver"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=50)),
                ("record_id", models.PositiveIntegerField(blank=True, null=True)),
                ("previous_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
