# Generated by Django 4.2.9 on 2026-03-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeanalytics",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_analytics",
                to="school.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="dailycollectionreport",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_reports",
                to="school.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="arrearssummary",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrears_summary",
                to="school.student",
            ),
        ),
        migrations.AddIndex(
            model_name="feeanalytics",
            index=models.Index(
                fields=["school_class"], name="fee_analyti_school__221f1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailycollectionreport",
            index=models.Index(
                fields=["school_class", "report_date"],
                name="daily_colle_school__5a7cf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrearssummary",
            index=models.Index(
                fields=["student"], name="arrears_sum_student_a52adf_idx"
            ),
        ),
    ]
