# Generated by Django 4.2.9 on 2026-03-07 10:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("GEN_STUDIES", "General Studies"),
                            ("JHS_EXTRA", "JHS Extra"),
                            ("JHS3_EXTRA", "JHS 3 Extra"),
                            ("SATURDAY", "Saturday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Share before attendance adjustment",
                        max_digits=10,
                    ),
                ),
                (
                    "adjusted_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final share after attendance adjustment",
                        max_digits=10,
                    ),
                ),
                ("attendance_status", models.CharField(blank=True, max_length=20)),
                (
                    "attendance_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=3
                    ),
                ),
                ("special_share_type", models.CharField(blank=True, max_length=50)),
                (
                    "special_share_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("calculation_log", models.JSONField(default=dict)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "distributions",
            },
        ),
        migrations.CreateModel(
            name="FeeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("GEN_STUDIES", "General Studies"),
                            ("JHS_EXTRA", "JHS Extra"),
                            ("JHS3_EXTRA", "JHS 3 Extra"),
                            ("SATURDAY", "Saturday"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXPECTED", "Expected"),
                            ("PAID_FULL", "Paid (Full)"),
                            ("PAID_PARTIAL", "Paid (Partial)"),
                            ("EXEMPT", "Exempt"),
                            ("WAIVED", "Waived"),
                            ("UNPAID", "Unpaid"),
                        ],
                        db_index=True,
                        default="EXPECTED",
                        max_length=20,
                    ),
                ),
                (
                    "unpaid_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_MONEY", "No Money"),
                            ("FORGOT", "Forgot"),
                            ("PARENT_ISSUE", "Parent Issue"),
                            ("ABSENT", "Student Absent"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unpaid_notes", models.TextField(blank=True)),
                ("waiver_reason", models.TextField(blank=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("receipt_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fee_collections",
            },
        ),
        migrations.CreateModel(
            name="FeePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("GEN_STUDIES", "General Studies"),
                            ("JHS_EXTRA", "JHS Extra"),
                            ("JHS3_EXTRA", "JHS 3 Extra"),
                            ("SATURDAY", "Saturday"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("academic_year", models.CharField(max_length=20)),
                ("term", models.CharField(blank=True, max_length=20)),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_distributed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "school_retention_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Percentage retained by school",
                        max_digits=5,
                    ),
                ),
                (
                    "admin_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Administrative fee percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "eligible_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles eligible for distribution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fee Pool",
                "verbose_name_plural": "Fee Pools",
                "db_table": "fee_pools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PoolSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("GEN_STUDIES", "General Studies"),
                            ("JHS_EXTRA", "JHS Extra"),
                            ("JHS3_EXTRA", "JHS 3 Extra"),
                            ("SATURDAY", "Saturday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_expected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "school_retention",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "administrative_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_distributed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("recipient_count", models.PositiveIntegerField()),
                ("calculation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("calculation_log", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "pool_summaries",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular School Day"),
                            ("SATURDAY", "Saturday Class"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISTRIBUTED", "Distributed"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_count", models.PositiveIntegerField(default=0)),
                ("last_unlock_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LATE", "Late"),
                            ("SICK", "Sick"),
                            ("PERMISSION", "Permission"),
                            ("OFFICIAL_DUTY", "Official Duty"),
                            ("ABSENT", "Absent"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "documentation",
                    models.FileField(
                        blank=True, null=True, upload_to="attendance_docs/%Y/%m/"
                    ),
                ),
                ("documentation_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_attendance",
            },
        ),
        migrations.CreateModel(
            name="StudentArrears",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_type", models.CharField(max_length=20)),
                ("amount_owed", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("waiver_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_fee_collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arrears_records",
                        to="fees.feecollection",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrears",
                        to="fees.session",
                    ),
                ),
            ],
            options={
                "db_table": "student_arrears",
                "ordering": ["-session__date", "student"],
            },
        ),
    ]
