# Generated by Django 4.2.9 on 2026-03-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentarrears",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrears",
                to="school.student",
            ),
        ),
    ]
