# Generated by Django 4.2.9 on 2026-03-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentarrears",
            name="waived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="fees.session",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="opened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opened_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="poolsummary",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_summaries",
                to="fees.session",
            ),
        ),
        migrations.AddField(
            model_name="feepool",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_fee_pools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feecollection",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feecollection",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_collections",
                to="school.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="feecollection",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_collections",
                to="fees.session",
            ),
        ),
        migrations.AddField(
            model_name="feecollection",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_collections",
                to="school.student",
            ),
        ),
        migrations.AddField(
            model_name="feecollection",
            name="waiver_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_waivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distributions_paid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="fees.session",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentarrears",
            index=models.Index(
                fields=["student", "status"], name="student_arr_student_999f0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentarrears",
            index=models.Index(fields=["status"], name="student_arr_status_cde9c0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="studentarrears",
            unique_together={("student", "session", "pool_type")},
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["date", "status"], name="staff_atten_date_5ba088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["staff", "date"], name="staff_atten_staff_i_ff7ba3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together={("staff", "date")},
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["date", "status"], name="sessions_date_4ae278_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_type", "date"], name="sessions_session_985529_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="poolsummary",
            unique_together={("session", "pool_type")},
        ),
        migrations.AddIndex(
            model_name="feecollection",
            index=models.Index(
                fields=["session", "school_class"],
                name="fee_collect_session_f81ef0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feecollection",
            index=models.Index(
                fields=["session", "pool_type"], name="fee_collect_session_fb5be4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feecollection",
            index=models.Index(
                fields=["student", "session"], name="fee_collect_student_b36a8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feecollection",
            index=models.Index(fields=["status"], name="fee_collect_status_63484f_idx"),
        ),
        migrations.AddIndex(
            model_name="feecollection",
            index=models.Index(
                fields=["receipt_number"], name="fee_collect_receipt_48e769_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feecollection",
            unique_together={("session", "student", "pool_type")},
        ),
        migrations.AddIndex(
            model_name="distribution",
            index=models.Index(
                fields=["session", "pool_type"], name="distributio_session_9c2018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="distribution",
            index=models.Index(
                fields=["staff", "session"], name="distributio_staff_i_39e670_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="distribution",
            index=models.Index(
                fields=["is_paid"], name="distributio_is_paid_358aa2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="distribution",
            unique_together={("session", "pool_type", "staff")},
        ),
    ]
