# Generated by Django 4.2.9 on 2026-03-07 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fees", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaturdayAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("is_present", models.BooleanField(default=False)),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "saturday_attendance",
            },
        ),
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="documentation_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffattendance",
            name="documentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attendance_docs/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["session"], name="staff_atten_session_d06a84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffattendance",
            constraint=models.UniqueConstraint(
                fields=("staff", "date"), name="uniq_staff_attendance_per_day"
            ),
        ),
        migrations.AddField(
            model_name="saturdayattendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_saturday_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saturdayattendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday_attendances",
                to="fees.session",
            ),
        ),
        migrations.AddField(
            model_name="saturdayattendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="saturdayattendance",
            index=models.Index(
                fields=["date", "is_present"], name="saturday_at_date_a72bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saturdayattendance",
            index=models.Index(
                fields=["staff", "date"], name="saturday_at_staff_i_663b58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saturdayattendance",
            index=models.Index(
                fields=["session"], name="saturday_at_session_bbb129_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="saturdayattendance",
            constraint=models.UniqueConstraint(
                fields=("staff", "date"), name="uniq_staff_saturday_attendance_per_day"
            ),
        ),
    ]
