# Generated by Django 4.2.9 on 2026-03-07 18:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0004_saturdayattendance_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="distribution",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="feecollection",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="poolsummary",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="studentarrears",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="feepool",
            name="admin_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.00"),
                help_text="Administrative fee percentage",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="distribution",
            constraint=models.UniqueConstraint(
                fields=("session", "pool_type", "staff"),
                name="uniq_session_pool_staff_distribution",
            ),
        ),
        migrations.AddConstraint(
            model_name="feecollection",
            constraint=models.UniqueConstraint(
                fields=("session", "student", "pool_type"),
                name="uniq_session_student_pool_fee_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="poolsummary",
            constraint=models.UniqueConstraint(
                fields=("session", "pool_type"), name="uniq_session_pool_summary"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentarrears",
            constraint=models.UniqueConstraint(
                fields=("student", "session", "pool_type"),
                name="uniq_student_session_pool_arrears",
            ),
        ),
    ]
